apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 371162891584.dkr.ecr.ap-southeast-1.amazonaws.com/demo-frontend
  newName: 371162891584.dkr.ecr.ap-southeast-1.amazonaws.com/demo-frontend
  newTag: 168675b4
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
